# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ub3FsfHNXaXWbxLFqydngfc_EmRWu2GZ
"""

print("hello")